### PR TITLE
Fix IGV Viewing Archived File

### LINKED ISSUE #51: dx generate download link will fail for archived bam sample
Bug location: IGV page
Situation
When entering sample name (e.g. X219574), if backend result in one file (archived or live state) rather than a list of files matching the keyword, it will try to generate dnanexus download link on that one file. This works fine if the file is in live state but will cause error if file-id is in archived state.

### PR DESCRIPTION
**Pull request by JasonLing95**
- remove IVA reference
- update requirements.txt
- include try except else clause in get_dx_url because archived file will fail and we return None if so

Fix #51 

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/52)

### CODE REVIEW

**Comment by JasonLing95** [comment]
This version is on dev (2.0.1)

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/52)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @JasonLing95)

___
*[`DNAnexus_to_igv/views.py` line 198 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/52#-NSKsK4WABtGXzDZdJF_:-NSKsK4WABtGXzDZdJFa:bxzwgqe) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/44b6be0b97982f69e08b9559725eb427e84bce7a/DNAnexus_to_igv/views.py#L198)):*
> ```Python
> 
>     else:
>         logger.error(
> ```

when I search for X219573 (which I know is archived) I get this error message appear, and it doesn't either have the error message from DNAnexus or explicitly say the bam couldn't be loaded as it is archived, is the above with `dx.exceptions.InvalidState`?

also can we increase the timeout for error banner messages, I think its like 5 seconds which for bigger messages seems a bit quick for someone to read it all and understand, maybe 10 would be better
___
*[`DNAnexus_to_igv/views.py` line 214 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/52#-NSKsy3k60kIy1AYGSGk:-NSKsy3k60kIy1AYGSGl:b-thw7rq) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/44b6be0b97982f69e08b9559725eb427e84bce7a/DNAnexus_to_igv/views.py#L214)):*
> ```Python
>     context_dict["url_form"] = UrlForm()
>     context_dict["desk"] = GRID_SERVICE_DESK
>     context_dict["iva"] = GRID_IVA
> ```

can this go?



_Code quote:_
```Python
context_dict["iva"] = GRID_IVA
```
___
*[`DNAnexus_to_igv/views.py` line 230 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/52#-NSKt-780hRX9RLofmUZ:-NSKt-780hRX9RLofmU_:b-thw7rq) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/44b6be0b97982f69e08b9559725eb427e84bce7a/DNAnexus_to_igv/views.py#L230)):*
> ```Python
>         context_dict["url_form"] = UrlForm()
>         context_dict["desk"] = GRID_SERVICE_DESK
>         context_dict["iva"] = GRID_IVA
> ```

can this go?



_Code quote:_
```Python
context_dict["iva"] = GRID_IVA
```
___
*[`DNAnexus_to_igv/views.py` line 542 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/52#-NSKt6LF2W_Ak9_p3Bw7:-NSKt6LF2W_Ak9_p3Bw8:b-58so6z) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/44b6be0b97982f69e08b9559725eb427e84bce7a/DNAnexus_to_igv/views.py#L542)):*
> ```Python
>     ]
> 
>     print(selected_sample)
> ```

needed?



_Code quote:_
```Python
   print(selected_sample)
```

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/52)* status: 4 of 26 files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[`DNAnexus_to_igv/views.py` line 198 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/52#-NSKsK4WABtGXzDZdJF_:-NSL5ne17y0sVQJVmUdG:bew58ah) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/44b6be0b97982f69e08b9559725eb427e84bce7a/DNAnexus_to_igv/views.py#L198)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

when I search for X219573 (which I know is archived) I get this error message appear, and it doesn't either have the error message from DNAnexus or explicitly say the bam couldn't be loaded as it is archived, is the above with `dx.exceptions.InvalidState`?

also can we increase the timeout for error banner messages, I think its like 5 seconds which for bigger messages seems a bit quick for someone to read it all and understand, maybe 10 would be better
</blockquote></details>

increased timeout to 10s

this error message wont be showed in the frontend to the user, just logged in the error log file.
The only message the user will see is 'Error generating dnanexus download link. Please contact helpdesk'
___
*[`DNAnexus_to_igv/views.py` line 214 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/52#-NSKsy3k60kIy1AYGSGk:-NSL5kbD4PhFh7l0HhDe:b4nm0ny) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/44b6be0b97982f69e08b9559725eb427e84bce7a/DNAnexus_to_igv/views.py#L214)):*
> X219573
removed
___
*[`DNAnexus_to_igv/views.py` line 230 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/52#-NSKt-780hRX9RLofmUZ:-NSL5ldq4zXxfmXX8n7Q:b-hfpv0l) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/44b6be0b97982f69e08b9559725eb427e84bce7a/DNAnexus_to_igv/views.py#L230)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can this go?
</blockquote></details>

removed
___
*[`DNAnexus_to_igv/views.py` line 542 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/52#-NSKt6LF2W_Ak9_p3Bw7:-NSL5mnd0trU5OsGP5d3:b-hfpv0l) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/44b6be0b97982f69e08b9559725eb427e84bce7a/DNAnexus_to_igv/views.py#L542)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

needed?
</blockquote></details>

removed

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/52)* status: 12 of 26 files reviewed, 4 unresolved discussions (waiting on @JasonLing95)

___
*[`DNAnexus_to_igv/views.py` line 198 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/52#-NSKsK4WABtGXzDZdJF_:-NSL9mSE5SAUrBIDq5C2:b-112v5v) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/44b6be0b97982f69e08b9559725eb427e84bce7a/DNAnexus_to_igv/views.py#L198)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

increased timeout to 10s

this error message wont be showed in the frontend to the user, just logged in the error log file.
The only message the user will see is 'Error generating dnanexus download link. Please contact helpdesk'
</blockquote></details>

I think if it is archived we should show that to them, then when they raise a ticket we know straight away its just unarchiving thats needed and we don't need to go debug anything.

It also lets the user know its just a file thats archived and not a bug as it will happen reasonably often

**Review by jethror1 — COMMENTED** [review]
> Reviewed 12 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/52)* status: 24 of 26 files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/52)* status: 24 of 26 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`DNAnexus_to_igv/views.py` line 198 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/52#-NSKsK4WABtGXzDZdJF_:-NSLaKqE9gBDQRNZSXc4:b2z76kd) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/44b6be0b97982f69e08b9559725eb427e84bce7a/DNAnexus_to_igv/views.py#L198)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I think if it is archived we should show that to them, then when they raise a ticket we know straight away its just unarchiving thats needed and we don't need to go debug anything.

It also lets the user know its just a file thats archived and not a bug as it will happen reasonably often
</blockquote></details>

fixed to show the returned error message so that it can be copied when raising a ticket

**Comment by JasonLing95** [comment]
Error Message now looks like this

Screenshot from 2023-04-11 11-18-10

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/52)* status: 21 of 26 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`DNAnexus_to_igv/views.py` line 198 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/52#-NSKsK4WABtGXzDZdJF_:-NSkBvfO48zDp_2MR0Di:bqminba) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/44b6be0b97982f69e08b9559725eb427e84bce7a/DNAnexus_to_igv/views.py#L198)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

fixed to show the returned error message so that it can be copied when raising a ticket
</blockquote></details>

gave top some margin for the error message

**Pull request merged**
