### PR TITLE
ldap login 

### PR DESCRIPTION
**Pull request by JasonLing95**
# Updates
- add ldap login for igv pages
- remove GRID_BLOG and GRID_PROJECT
- install vim in cron container
- added db container in docker-compose.yml because login requires it 
- added envs required for LDAP to work (BIND_DN, BIND_PASSWORD, AUTH_LDAP..)

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/genetics_ark/44)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 31 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/genetics_ark/44)* status: 31 of 37 files reviewed, 5 unresolved discussions (waiting on @JasonLing95)

___
*[`ga_core/settings.py` line 37 at r1](https://reviewable.io/reviews/eastgenomics/genetics_ark/44#-NJFWztz137apOlzsSFa:-NJFWztz137apOlzsSFb:b-cyubvo) ([raw file](https://github.com/eastgenomics/genetics_ark/blob/bc50c9ad7e08ffd49a0827f2a87e86eeb512d6e2/ga_core/settings.py#L37)):*
> ```Python
>         origin.strip() for origin in CSRF_TRUSTED_ORIGINS.split(',')]
> 
>     # GOOGLE_ANALYTICS = os.environ['GOOGLE_ANALYTICS']
> ```

we can remove google analytics things since they will be blocked by the firewall



_Code quote:_
```Python
# GOOGLE_ANALYTICS = os.environ['GOOGLE_ANALYTICS']
```
___
*[`ga_core/settings.py` line 202 at r1](https://reviewable.io/reviews/eastgenomics/genetics_ark/44#-NJFXARABodtGS6UUBEm:-NJFXARABodtGS6UUBEn:b-58so6z) ([raw file](https://github.com/eastgenomics/genetics_ark/blob/bc50c9ad7e08ffd49a0827f2a87e86eeb512d6e2/ga_core/settings.py#L202)):*
> ```Python
> LOGIN_REDIRECT_URL = '/genetics_ark/igv'
> 
> # AUTHENTICATION_BACKENDS = (
> ```

needed?



_Code quote:_
```Python
# AUTHENTICATION_BACKENDS = (
#     'django_auth_ldap.backend.LDAPBackend',
# )
```
___
*[`ga_core/settings.py` line 209 at r1](https://reviewable.io/reviews/eastgenomics/genetics_ark/44#-NJFXGKvEByILSpHraef:-NJFXGKwEbRBsfZ5GFRj:b46p4q2) ([raw file](https://github.com/eastgenomics/genetics_ark/blob/bc50c9ad7e08ffd49a0827f2a87e86eeb512d6e2/ga_core/settings.py#L209)):*
> ```Python
> AUTH_LDAP_CONNECTION_OPTIONS = {ldap.OPT_REFERRALS: 0}
> 
> AUTH_LDAP_SERVER_URI = "ldap://net.addenbrookes.nhs.uk"
> ```

should this be in the config? 



_Code quote:_
```Python
"ldap://net.addenbrookes.nhs.uk"
```
___
*[`ga_core/settings.py` line 214 at r1](https://reviewable.io/reviews/eastgenomics/genetics_ark/44#-NJFXJci19Kz29gbdjST:-NJFXJci19Kz29gbdjSU:beckiag) ([raw file](https://github.com/eastgenomics/genetics_ark/blob/bc50c9ad7e08ffd49a0827f2a87e86eeb512d6e2/ga_core/settings.py#L214)):*
> ```Python
> 
> AUTH_LDAP_USER_SEARCH = LDAPSearch(
>     "ou=addenbrookes,dc=net,dc=addenbrookes,dc=nhs,dc=uk",
> ```

can this string go in the config too? something like `LDAP_CONF` would be fine



_Code quote:_
```Python
ou=addenbrookes,dc=net,dc=addenbrookes,dc=nhs,dc=uk",
```
___
*[`ga_core/settings.py` line 219 at r1](https://reviewable.io/reviews/eastgenomics/genetics_ark/44#-NJFXVfaCIrh7-DHqE2C:-NJFXVfaCIrh7-DHqE2D:b22rona) ([raw file](https://github.com/eastgenomics/genetics_ark/blob/bc50c9ad7e08ffd49a0827f2a87e86eeb512d6e2/ga_core/settings.py#L219)):*
> ```Python
> )
> 
> SESSION_EXPIRE_AT_BROWSER_CLOSE = False
> ```

does this mean they will only be prompted to login every 26 weeks? reasoning for this?



_Code quote:_
```Python
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# Age of cookie, in seconds (default: 2 weeks, here set to 26 weeks).
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7 * 26
```

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/genetics_ark/44)* status: 28 of 39 files reviewed, 7 unresolved discussions (waiting on @JasonLing95)

___
*[`accounts/models.py` line 7 at r2](https://reviewable.io/reviews/eastgenomics/genetics_ark/44#-NJG52XPEyYlJK1HTbkB:-NJG52XPEyYlJK1HTbkC:bfse2ju) ([raw file](https://github.com/eastgenomics/genetics_ark/blob/c2de9d883ff4ecd55c6d02a8fce49f0b1b935775/accounts/models.py#L7)):*
> ```Python
> 
> 
> # class Profile(models.Model):
> ```

I assume this can all be deleted?



_Code quote:_
```Python
# class Profile(models.Model):
#     id = models.AutoField(primary_key=True)
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     first_name = models.CharField(max_length=100, blank=True)
#     last_name = models.CharField(max_length=100, blank=True)
#     email = models.EmailField(max_length=150)
#     signup_confirmation = models.BooleanField(default=False)

#     def __str__(self):
#         return self.user.username


# @receiver(post_save, sender=User)
# def update_profile_signal(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#     instance.profile.save()
```
___
*[`DNAnexus_to_igv/views.py` line 169 at r2](https://reviewable.io/reviews/eastgenomics/genetics_ark/44#-NJG5AVn8kv8YlYaZ1SM:-NJG5AVn8kv8YlYaZ1SN:b-5kxzy) ([raw file](https://github.com/eastgenomics/genetics_ark/blob/c2de9d883ff4ecd55c6d02a8fce49f0b1b935775/DNAnexus_to_igv/views.py#L169)):*
> ```Python
> 
> 
> # @login_required(redirect_field_name=None)
> ```

should this be commented out or was it just for testing?



_Code quote:_
```Python
i
```

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/genetics_ark/44)* status: 27 of 39 files reviewed, 7 unresolved discussions (waiting on @jethror1)

___
*[`accounts/models.py` line 7 at r2](https://reviewable.io/reviews/eastgenomics/genetics_ark/44#-NJG52XPEyYlJK1HTbkB:-NJGpFeS1K2O1J-zSpzD:b-9unw5o) ([raw file](https://github.com/eastgenomics/genetics_ark/blob/c2de9d883ff4ecd55c6d02a8fce49f0b1b935775/accounts/models.py#L7)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I assume this can all be deleted?
</blockquote></details>

deleted
___
*[`DNAnexus_to_igv/views.py` line 169 at r2](https://reviewable.io/reviews/eastgenomics/genetics_ark/44#-NJG5AVn8kv8YlYaZ1SM:-NJGpCX8E0xSvUrKp8j2:b-rdva32) ([raw file](https://github.com/eastgenomics/genetics_ark/blob/c2de9d883ff4ecd55c6d02a8fce49f0b1b935775/DNAnexus_to_igv/views.py#L169)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

should this be commented out or was it just for testing?
</blockquote></details>

uncommented for testing. commented in again
___
*[`ga_core/settings.py` line 37 at r1](https://reviewable.io/reviews/eastgenomics/genetics_ark/44#-NJFWztz137apOlzsSFa:-NJGpAvq6mNh23IRC-Ir:b-9unw5o) ([raw file](https://github.com/eastgenomics/genetics_ark/blob/bc50c9ad7e08ffd49a0827f2a87e86eeb512d6e2/ga_core/settings.py#L37)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

we can remove google analytics things since they will be blocked by the firewall
</blockquote></details>

deleted
___
*[`ga_core/settings.py` line 202 at r1](https://reviewable.io/reviews/eastgenomics/genetics_ark/44#-NJFXARABodtGS6UUBEm:-NJGp8vQD8whaxCbLZge:b-9unw5o) ([raw file](https://github.com/eastgenomics/genetics_ark/blob/bc50c9ad7e08ffd49a0827f2a87e86eeb512d6e2/ga_core/settings.py#L202)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

needed?
</blockquote></details>

deleted
___
*[`ga_core/settings.py` line 209 at r1](https://reviewable.io/reviews/eastgenomics/genetics_ark/44#-NJFXGKvEByILSpHraef:-NJGp6eM8SMmzLtUcny_:bskwqfn) ([raw file](https://github.com/eastgenomics/genetics_ark/blob/bc50c9ad7e08ffd49a0827f2a87e86eeb512d6e2/ga_core/settings.py#L209)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

should this be in the config? 
</blockquote></details>

edited to be in config
___
*[`ga_core/settings.py` line 214 at r1](https://reviewable.io/reviews/eastgenomics/genetics_ark/44#-NJFXJci19Kz29gbdjST:-NJGp4p59UjcXgbhr3qd:b2mm1vk) ([raw file](https://github.com/eastgenomics/genetics_ark/blob/bc50c9ad7e08ffd49a0827f2a87e86eeb512d6e2/ga_core/settings.py#L214)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can this string go in the config too? something like `LDAP_CONF` would be fine
</blockquote></details>

created in config
___
*[`ga_core/settings.py` line 219 at r1](https://reviewable.io/reviews/eastgenomics/genetics_ark/44#-NJFXVfaCIrh7-DHqE2C:-NJGpHk30cEb2nlzt387:b-guaff3) ([raw file](https://github.com/eastgenomics/genetics_ark/blob/bc50c9ad7e08ffd49a0827f2a87e86eeb512d6e2/ga_core/settings.py#L219)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

does this mean they will only be prompted to login every 26 weeks? reasoning for this?
</blockquote></details>

deleted because not relevant anymore

**Comment by JasonLing95** [comment]
deployed on dev

**Review by jethror1 — COMMENTED** [review]
> Reviewed 2 of 37 files at r1, 5 of 8 files at r2, 2 of 4 files at r3, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/genetics_ark/44)* status: 37 of 39 files reviewed, all discussions resolved

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 3 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/genetics_ark/44)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/genetics_ark/44)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/genetics_ark/44)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
