### PR TITLE
Install Vim on nginx container

### PR DESCRIPTION
**Pull request by JasonLing95**
# Changes
- install vim on nginx container for if we need to change the config file `nginx.conf`, we could just `docker exec -it` into the container and change it with vim then restart the container.
- Change Dockerfile to use primer designer 2.0.2

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/genetics_ark/42)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/genetics_ark/42)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

___
*[`nginx/nginx.conf` line 11 at r1](https://reviewable.io/reviews/eastgenomics/genetics_ark/42#-NFDzHoo4XJXfVw8qZ31:-NFDzHoo4XJXfVw8qZ32:b-n5un2k) ([raw file](https://github.com/eastgenomics/genetics_ark/blob/2ca5d016b62acb9385f5d86e6f3d5887efb9a127/nginx/nginx.conf#L11)):*
> ```Nginx
> 
>     # the domain name it will serve for to substitute ip
>     server_name dev-genomics.net.addenbrookes.nhs.uk;
> ```

should this config file be separate from the repo if we're storing addresses in it? or can you do something like have this as an env variable that is added at run time?

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/genetics_ark/42)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`nginx/nginx.conf` line 11 at r1](https://reviewable.io/reviews/eastgenomics/genetics_ark/42#-NFDzHoo4XJXfVw8qZ31:-NFE-5yk0igZgBAiUqQw:b-f02x7m) ([raw file](https://github.com/eastgenomics/genetics_ark/blob/2ca5d016b62acb9385f5d86e6f3d5887efb9a127/nginx/nginx.conf#L11)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

should this config file be separate from the repo if we're storing addresses in it? or can you do something like have this as an env variable that is added at run time? 
</blockquote></details>

my understanding (from reading around) is that the server_name doesn't really do much (https://serverfault.com/questions/1062957/is-server-name-really-needed-for-default-server-nginx) we could leave it empty too. The thing that control the host seems to be the port in docker-compose.yml and the host env in .env but I'm just installing the vim in nginx just in case we need to change anything in the future such as loggging directory or static file directory

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/genetics_ark/42)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

___
*[`nginx/nginx.conf` line 11 at r1](https://reviewable.io/reviews/eastgenomics/genetics_ark/42#-NFDzHoo4XJXfVw8qZ31:-NFE0pjvAqdpvQGGEurQ:betsu1) ([raw file](https://github.com/eastgenomics/genetics_ark/blob/2ca5d016b62acb9385f5d86e6f3d5887efb9a127/nginx/nginx.conf#L11)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

my understanding (from reading around) is that the server_name doesn't really do much (https://serverfault.com/questions/1062957/is-server-name-really-needed-for-default-server-nginx) we could leave it empty too. The thing that control the host seems to be the port in docker-compose.yml and the host env in .env but I'm just installing the vim in nginx just in case we need to change anything in the future such as loggging directory or static file directory
</blockquote></details>

could we remove it then just to remove confusion? (and also add a comment saying it's being left blank and where the server name is set from)

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/genetics_ark/42)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`nginx/nginx.conf` line 11 at r1](https://reviewable.io/reviews/eastgenomics/genetics_ark/42#-NFDzHoo4XJXfVw8qZ31:-NFEUzMD5iEBaNHUQN9X:b-hfpv0l) ([raw file](https://github.com/eastgenomics/genetics_ark/blob/2ca5d016b62acb9385f5d86e6f3d5887efb9a127/nginx/nginx.conf#L11)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

could we remove it then just to remove confusion? (and also add a comment saying it's being left blank and where the server name is set from)
</blockquote></details>

removed

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/genetics_ark/42)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
