### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by JasonLing95**
# Changes
- added checking if DNAnexus generated links is not `None` else return error message, previously will show `None` in frontend
- edited some href links and url paths

### CODE REVIEW

**Comment by JasonLing95** [comment]
Added
- copy error message to clipboard when clicking error message
- changed error message timeout to 15s
- every error message will include "Click here to contact helpdesk" which will link to the helpdesk

**Comment by JasonLing95** [comment]
Screenshot from 2022-08-02 14-39-06
Screenshot from 2022-08-02 14-39-02

**Comment by jethror1** [comment]
What does the copy button look like before copying?

Couuld you align the text into the center of the banner and have the contact us on a new line to make it clear.

Also can you add some text like "Please copy the above error message and contact the bioinformatics team by clicking here" to make it super obvious to them

**Comment by JasonLing95** [comment]
# Update
- cleaned up CSS
- added more text to click to copy button

**Comment by JasonLing95** [comment]
Screenshot from 2022-08-04 09-43-09

**Comment by JasonLing95** [comment]
Homepage now looks like this
Screenshot from 2022-08-04 09-45-48

**Comment by JasonLing95** [comment]
Added `backports.zoneinfo==0.2.1;python_version<"3.9"` because backports.zoninfo doesn't work well for `python>3.9`

**Comment by JasonLing95** [comment]
# Added env `GRID_SERVICE_DESK` `GRID_PROJECT` `GRID_BLOG` `GRID_IVA`

**Comment by JasonLing95** [comment]
dropdown now got this arrow
Screenshot from 2022-08-04 13-48-04

**Comment by JasonLing95** [comment]
# Fixed
- helpdesk link in error message doesn't point to helpdesk
Screenshot from 2022-08-05 15-14-42

**Comment by JasonLing95** [comment]
The version on dev server is currently running this PR (5/8/2022)

**Comment by JasonLing95** [comment]
# Added
- indexUrl in refseq track in IGV.js so that igv won't need to load the whole refseq everytime

**Pull request merged**
