### PR TITLE
IN-569: include primer name in output pdf

### PR DESCRIPTION
**Pull request by JasonLing95**
# Update
- include primer name into output PDF

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/66)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/66)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

___
*[`primer_designer/services.py` line 21 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/66#-Nw9upE-5-i6TnEl-Yfj:-Nw9upE0Du1C5h54_l71:b-58so6z) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/c6d97d6fbb3ccf8ee7ac3d0e7501eaacc86ee5ad/primer_designer/services.py#L21)):*
> ```Python
>         primer_cmd = f"python3 {PRIMER_PATH}/primer_designer_region.py {cmd}"
> 
>         print(primer_cmd)
> ```

needed?



_Code quote:_
```Python
print(primer_cmd)
```

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/66)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @JasonLing95)

___
*[`primer_designer/services.py` line 47 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/66#-Nw9vKlg5-hxI4inT35U:-Nw9vKlg5-hxI4inT35V:b-x8lqlt) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/c6d97d6fbb3ccf8ee7ac3d0e7501eaacc86ee5ad/primer_designer/services.py#L47)):*
> ```Python
>     Format region from input form as command (str) for primer designer
> 
>     Args: region (str): region passed from Input Form
> ```

missing dir arg from docstring



_Code quote:_
```Python
Args: region (str): region passed from Input Form
```

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/66)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`primer_designer/services.py` line 21 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/66#-Nw9upE-5-i6TnEl-Yfj:-NwA-X_24Uyt1dxSDJNV:bhvlts0) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/c6d97d6fbb3ccf8ee7ac3d0e7501eaacc86ee5ad/primer_designer/services.py#L21)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

needed?
</blockquote></details>

just made more convenient to look into the djangoq container on which command (chromosome, position, build) that failed the container - if it ever fail
___
*[`primer_designer/services.py` line 47 at r1](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/66#-Nw9vKlg5-hxI4inT35U:-NwA-k4e4ZTv18zue131:bb7f2mf) ([raw file](https://github.com/eastgenomics/Genetics_Ark/blob/c6d97d6fbb3ccf8ee7ac3d0e7501eaacc86ee5ad/primer_designer/services.py#L47)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

missing dir arg from docstring
</blockquote></details>

done

**Review by jethror1 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/66)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Genetics_Ark/66)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
